### ISSUE TITLE
Allow user to specify desired release when generating lists

### ISSUE THREAD

**Issue by guiscaranse** [xolox/python-apt-mirror-updater#10]
For Ubuntu-based spins (such as ElementaryOS), `apt-mirror-update` will raise a error due to the platform release name is different from Ubuntu.

For example: Running it on ElementaryOS will raise a `ValueError: The string 'hera' doesn't match a known Debian or Ubuntu release!`

Allowing users to overwrite the release when running `apt-mirror-updater` would fix this issue, for example: `apt-mirror-updater --release=bionic`

**Comment by xolox** [comment]
Hi Guilherme and thanks for the feedback. I've just published [apt-mirror-updater 7.2](https://apt-mirror-updater.readthedocs.io/en/latest/changelog.html#release-7-2-2020-04-18) which properly recognizes and supports Elementary OS. It knows which Elementary OS releases correspond to which Ubuntu releases so no release has to be specified.
