### ISSUE TITLE
Trusty not in old-releases

### ISSUE THREAD

**Issue by tarmack** [xolox/python-apt-mirror-updater#9]
python-apt-mirror-updater assumes that a release that is EOL needs to have its sources updated to the old-releases version. This is incorrect as the move to old-releases can be delayed by quite some time, especially for LTS releases apparently (and there seems to be no schedule set from Canonical).

I propose to add a verification that the repositories for the release are indeed available in old-releases before installing the old-releases sources. This would prevent breaking an otherwise functional system.

**Comment by martin68** [comment]
@tarmack my fork's this commit fixs it
https://github.com/martin68/apt-smart/commit/b19d73b10a12129d5debb9c93efbac0671e52b79

**Comment by xolox** [comment]
Hey Bart and thanks for the feedback. This has been fixed in release 7.1 which was just published.
